services:
#    parcel.example:
#        class: ParcelOrderBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
parameters:
    parcel_rest.parcel.class: ParcelOrderBundle\Entity\ParcelOrder
services:
    parcel_rest.parcel_form.handler:
        class: ParcelOrderBundle\Handler\ParcelFormHandler
        arguments:   ['@doctrine.orm.entity_manager',   %parcel_rest.parcel.class%, '@form.factory', 'ParcelOrderBundle\Form\ParcelOrderType']