ParcelOrderBundle\Entity\ParcelOrder:
    properties:
        parcelOrderHash:    
            - NotBlank: ~
            - NotNull: ~
            - Range: 
                min: 1 
                max: 99999
                maxMessage: "The idSender value must be smaller or equal to 99999"
        notes:    
            - Length: 
                min: 1 
                max: 99999
                maxMessage: "Your note must be smaller or equal to 99999 signs"            